Update SVN Script

diff --git a/bin/svn-push b/bin/svn-push
--- a/bin/svn-push
+++ b/bin/svn-push
@@ -1,52 +1,44 @@
-#! /bin/bash
-# A modification of Dean Clatworthy's deploy script as found here: https://github.com/deanc/wordpress-plugin-git-svn
-# The difference is that this script lives in the plugin's git repo & doesn't require an existing SVN repo.
+#!/bin/bash
+# Given a svn-url file one directory up, export the latest git commits to the specified SVN repo.
+# Create a git release tag from the version specified in the plugin file.
+# Author: Weston Ruter (@westonruter)
 
-# main config
-export PLUGINSLUG="rtbiz"  #must match with wordpress.org plugin slug
-export MAINFILE="index.php" # this should be the name of your main php file in the wordpress plugin
-#SVNUSER="rtcamp" # your svn username
+set -e
 
-##### YOU CAN STOP EDITING HERE #####
-CURRENTDIR=`pwd`
+cd "$( dirname $0 )"
+dev_lib_dir=$(pwd)
+cd ..
 
-# git config
-GITPATH="$CURRENTDIR/" # this file should be in the base of your git repository
-
-# svn config
-SVNPATH="/tmp/$PLUGINSLUG" # path to a temp SVN repo. No trailing slash required and don't add trunk.
-SVNURL="https://plugins.svn.wordpress.org/$PLUGINSLUG/" # Remote SVN repo on wordpress.org, with no trailing slash
-
-# Detect svn username based on url
-SVNUSER=$(cat ~/.subversion/auth/svn.simple/* | grep -A4 $(echo $SVNURL | awk -F// '{print $2}' | cut     -d'/' -f1) | tail -n1)
-if [ -z "$SVNUSER" ]
-then
-	SVNUSER="rtcamp"
+if [ ! -e svn-url ]; then
+	echo "Error: Missing svn-url file" >&2
+	exit 1
 fi
 
-# Let's begin...
-echo ".........................................."
-echo
-echo "Preparing to deploy wordpress plugin"
-echo
-echo ".........................................."
-echo
+force=
+while getopts 'f' option; do
+	case $option in
+		f)
+			force=1
+			;;
+	esac
+done
 
-# Check version in readme.txt is the same as plugin file
-NEWVERSION1=`grep "^Stable tag" $GITPATH/readme.txt | awk -F' ' '{print $3}'`
-echo "readme version: $NEWVERSION1"
-#NEWVERSION2=`grep "^Version" $GITPATH/$MAINFILE | awk -F' ' '{print $2}'`
-NEWVERSION2=`grep -i "Version" $GITPATH/$MAINFILE | head -n1 | awk -F':' '{print $2}' | awk -F' ' '{print $1}'`
-echo "$MAINFILE version: $NEWVERSION2"
+current_branch=$(git rev-parse --abbrev-ref HEAD)
+if [ $current_branch != 'master' ]; then
+	echo "Please checkout the master branch"
+	exit 1
+fi
 
-if [ "$NEWVERSION1" != "$NEWVERSION2" ]; then echo "Versions don't match. Exiting...."; exit 1; fi
+if [ -n "$(git status -s -uno)" ] && [ -z "$force" ]; then
+	git status
+	echo "Error: Git state has modified or staged files. Commit or reset, or supply -f" >&2
+	exit 1
+fi
 
-echo "Versions match in readme.txt and PHP file. Let's proceed..."
-
-cd $GITPATH
+git_root=$(pwd)
 
 if [ -e readme.txt ]; then
-	bin/generate-markdown-readme
+	$dev_lib_dir/generate-markdown-readme
 	git add readme.md
 fi
 if [ -n "$(git status --porcelain readme.md)" ]; then
@@ -54,44 +46,105 @@ if [ -n "$(git status --porcelain readme.md)" ]; then
 	exit 1
 fi
 
-echo -e "Enter a commit message for this new version: \c"
-read COMMITMSG
-git commit -am "$COMMITMSG"
-
-echo "Tagging new version in git"
-git tag -a "$NEWVERSION1" -m "Tagging version $NEWVERSION1"
-
-echo "Pushing latest commit to origin, with tags"
+git pull --ff-only origin master
 git push origin master
-git push origin master --tags
+svn_url=$(cat svn-url)
+svn_tmp_repo_dir=/tmp/svn-$(basename $git_root)-$(md5sum <<< $git_root | cut -c1-32)
+git_tmp_repo_dir=/tmp/git-$(basename $git_root)-$(md5sum <<< $git_root | cut -c1-32)
+echo "Temp SVN dir: $svn_tmp_repo_dir"
+echo "Temp Git dir: $git_tmp_repo_dir"
 
-echo "Creating local copy of SVN repo ..."
-svn co $SVNURL $SVNPATH
+for php in *.php; do
+	if grep -q 'Plugin Name:' $php && grep -q 'Version:' $php; then
+		plugin_version=$(cat $php | grep 'Version:' | sed 's/.*Version: *//')
+	fi
+done
 
-echo "Exporting the HEAD of master from git to the trunk of SVN"
-git checkout-index -a -f --prefix=$SVNPATH/trunk/
-
-echo "Ignoring github specific files and deployment script"
-svn propset svn:ignore -R -F $GITPATH/.svnignore "$SVNPATH/trunk/"
-
-if [ -e $GITPATH/assets/ ]; then
-	mkdir -p $SVNPATH/assets/
-	rsync -avz --delete $GITPATH/assets/ $SVNPATH/assets/
+if [ -z "$plugin_version" ]; then
+	echo "Unable to find plugin version"
+	exit 1
 fi
 
-echo "Changing directory to SVN and committing to trunk"
-cd $SVNPATH/trunk/
-# Add all new files that are not set to be ignored
-svn status | grep -v "^.[ \t]*\..*" | grep "^?" | awk '{print $2}' | xargs svn add
-svn commit --username=$SVNUSER -m "$COMMITMSG"
+if ! grep -q "$plugin_version" readme.txt; then
+	echo "Please update readme.txt to include $plugin_version in changelog"
+	exit 1
+fi
 
-echo "Creating new SVN tag & committing it"
-cd $SVNPATH
-svn copy trunk/ tags/$NEWVERSION1/
-cd $SVNPATH/tags/$NEWVERSION1
-svn commit --username=$SVNUSER -m "Tagging version $NEWVERSION1"
+if git show-ref --tags --quiet --verify -- "refs/tags/$plugin_version"; then
+	has_tag=1
+fi
 
-echo "Removing temporary directory $SVNPATH"
-rm -fr $SVNPATH/
+if [ -n "$has_tag" ] && [ -z "$force" ]; then
+	echo "Plugin version $plugin_version already tagged. Please bump version and try again, or supply -f"
+	exit 1
+fi
 
-echo "*** FIN ***"
+# Clean up existing Git and SVN repos
+if [ -e $svn_tmp_repo_dir ] && [ ! -e $svn_tmp_repo_dir/.svn ]; then
+	rm -rf $svn_tmp_repo_dir
+fi
+if [ -e $git_tmp_repo_dir ] && [ ! -e $git_tmp_repo_dir/.git ]; then
+	rm -rf $git_tmp_repo_dir
+fi
+
+# SVN: Checkout or update
+if [ ! -e $svn_tmp_repo_dir ]; then
+	svn checkout $svn_url $svn_tmp_repo_dir
+	cd $svn_tmp_repo_dir
+else
+	cd $svn_tmp_repo_dir
+	svn up
+fi
+
+# Git: Clone or pull
+if [ ! -e $git_tmp_repo_dir ]; then
+	git clone $git_root $git_tmp_repo_dir
+	cd $git_tmp_repo_dir
+else
+	cd $git_tmp_repo_dir
+	git pull
+fi
+
+# rsync all committed files from the Git repo to SVN
+rsync -avz --delete --delete-excluded --exclude '/assets' --exclude '/.git*' --exclude '/dev-lib' --exclude '/.jshint*' --exclude '/svn-url' --exclude '/.travis.yml' $git_tmp_repo_dir/ $svn_tmp_repo_dir/trunk/
+if [ -e $git_tmp_repo_dir/assets/ ]; then
+	mkdir -p $svn_tmp_repo_dir/assets/
+	rsync -avz --delete $git_tmp_repo_dir/assets/ $svn_tmp_repo_dir/assets/
+fi
+cd $svn_tmp_repo_dir
+
+if svn status | grep -s '^!'; then
+    svn status | grep '^!' | awk '{print $2}' | xargs svn delete --force
+fi
+svn add --force trunk --auto-props --parents --depth infinity -q
+
+mkdir -p tags
+if [ -e tags/$plugin_version ]; then
+	svn rm --force tags/$plugin_version
+fi
+cp -r trunk tags/$plugin_version
+svn add --force tags/$plugin_version --auto-props --parents --depth infinity -q
+
+svn_commit_file=/tmp/svn-commit-msg
+git --git-dir $git_root/.git log -1 --format="Update to commit %h from $(git --git-dir $git_root/.git config --get remote.origin.url)" > $svn_commit_file
+
+svn status
+echo
+echo "SVN Commit message:"
+cat $svn_commit_file
+echo
+
+echo "Hit enter to proceed with SVN commit and Git tag"
+read OK
+
+if [ -z "$has_tag" ]; then
+	cd $git_tmp_repo_dir
+	echo "Tagging plugin version $plugin_version"
+	git tag "$plugin_version" master
+	git push origin "$plugin_version"
+	cd $svn_tmp_repo_dir
+else
+	echo "Skipping plugin tag $plugin_version since already exists"
+fi
+
+svn commit -F $svn_commit_file
